### PR TITLE
Tk 38: update rss feed (formatting and performance)

### PR DESCRIPTION
**Pull request by mjohnson324-ingenovis**
Jira Ticket(s): 

[TK-38](https://fastaff.atlassian.net/browse/TK-38)

Issue:

- The Indeed RSS feed requires an update. The feed generates slowly, and the formatting and certain fields also require updates.

Fix:

- Create a method for retrieving all jobs at once. The current approach makes a request to Trustaff for every job  that gets added to the feed.
- Make updates to the generated XML as appropriate.

### CODE REVIEW

**Review by trustaff — CHANGES_REQUESTED** [review]
Michael, this looks good. However; there is an issue with the way you putting together the Job description..
Maybe you meant to replace the Specialty name from Goldmine with the one from JobDscription function, sicne the goldmine data is not updated, Specialty name need to come from the API call. and update your table. 
Secondly, you don't need to concatenate the Job specialty to the Job description. The description already contain the Specialty name  
#1 this line of code need to change from 
`Row("Description") = Row("SpecialtyName").ToString() & CurrentJob`
to 
`Row("Description") =  CurrentJob`

**Comment by mjohnson324-ingenovis** [comment]
> Michael, this looks good. However; there is an issue with the way you putting together the Job description.. Maybe you meant to replace the Specialty name from Goldmine with the one from JobDscription function, sicne the goldmine data is not updated, Specialty name need to come from the API call. and update your table. Secondly, you don't need to concatenate the Job specialty to the Job description. The description already contain the Specialty name #1 this line of code need to change from `Row("Description") = Row("SpecialtyName").ToString() & CurrentJob` to `Row("Description") = CurrentJob`

How's it look now?

**Review by trustaff — CHANGES_REQUESTED** [review]
Michael, there is still one last thing we need to do, the xml header need to match how they want it to be. please refer to Sam's recent notes 
Indeed
Indeed

**Comment by mjohnson324-ingenovis** [comment]
> Michael, there is still one last thing we need to do, the xml header need to match how they want it to be. please refer to Sam's recent notes Indeed Indeed

On it. I tried making that change earlier but had issues with adding the string.

**Comment by trustaff** [comment]
Approved pull request.

**Pull request merged**
